### ISSUE TITLE
FlatMap not indexed even if its contents are indexed

### ISSUE THREAD

**Issue by ebkalderon** [rayon-rs/rayon#399] opened 2017-08-03 23:52 UTC
I ran into this little papercut while using Rayon. It seems strange that `FlatMap` doesn't implement `IndexedParallelIterator` even if all its contents do. This prevents me from doing things like this:

```rust
let iters: Vec<SomeIndexedParIterThing> = Vec::new();
iters.into_par_iter()
    .flat_map(|iter| iter)  // <--- Merge the indexed iterators into one long iterator
    .enumerate()            // <--- Error: `FlatMap` is doesn't implement `IndexedParallelIterator`
    .for_each(|i, item| { ... });
```

I could work around this by iterating over each element in `iters` sequentially and `Chain` them together instead of `FlatMap`, but the `SomeIndexedParIterThing` type above is far too long to be named explicitly.  It would be very nice to make `FlatMap` indexed as long as its contents are indexed as well. Is this at all achievable in stable Rust without impl specialization?

**Comment by cuviper** [comment] 2017-08-04 00:19
In general, it's not possible, because we can't know the length of each item that will be flat-mapped until we evaluate the given closure.  So for example, when we split the iterator in half to hand to different threads, we don't know where "half" is, nor where the `enumerate()` indexes should start on the latter side.

I think perhaps there *could* be some special-purpose iterator for cases like you show, if we made it specific to `Vec<T> where T: IndexedParallelIterator`.  It would have to iterate itself to add up its total length, and then to find particular indexes to split at.  And inevitably some of those split indexes will be in the middle of one of the flat-mapped iters.  I imagine the producer for this something like:

```rust
struct FlatVec<I: IndexedParallelIterator> {
    head: Option<I::Producer>,
    mid: rayon::vec::IntoIter<I>,
    tail: Option<I::Producer>,
}
```

... except `I::Producer` doesn't exist -- we'd need associated type constructors.  That's why we have the messier `with_producer` callbacks instead.

You've got me in a loop -- "not possible. well... no... but maybe? no..."  It's an interesting problem, and feels like there should be a way, but I can't see how. (at least not as rayon is currently architected).

**Comment by cuviper** [comment] 2017-10-17 01:12
In the interest of cleaning up issues, I'm going to close this as "working as designed."  Without some clever new design, `FlatMap` will continue as unindexed only.

**Closed by cuviper** 2017-10-17 01:12 UTC
