### ISSUE TITLE
`0...10.map(foo).into_par_iter()` does not work (among others)

### ISSUE THREAD

**Issue by gnzlbg** [rayon-rs/rayon#439] opened 2017-09-14 19:37 UTC
I have some code that looks like this:

```rust
fn foo() -> impl ExactSizeIterator { /* some private implementation details */ }
fn bar() -> std::iter::Map<std::ops::Range<usize>, fn(usize) -> Idx> {
   /* more private implementation details */
}
```

for which I obviously cannot do `bar().into_par_iter()`. I've ended up adding a `_par()` variant of all these functions just to be able to use rayon, but the crux of the issue is that:

```rust
0..10.map(foo).into_par_iter()
```

and similar code does not work. I consider this to be a major deficiency in the library.

**Comment by cuviper** [comment] 2017-09-14 19:52
We can't see inside `std::iter;:Map`, so the only way I can imagine this is with support for arbitrary `Iterator` providers -- #46 -- but `.into_par_iter().map(foo)` will almost surely be faster.

**Comment by gnzlbg** [comment] 2017-09-14 20:05
> but .into_par_iter().map(foo) will almost surely be faster.

In, for example,  `0..10.map(|v| v *2).into_iter_par()` we build an IntoParallelIterator<Map<Range>, closure>` where `IntoParallelIterator` "somehow" can spit the underlying iterator into chunks. That is, the `.map` is evaluated in parallel.

**Comment by cuviper** [comment] 2017-09-14 20:47
> where `IntoParallelIterator` "somehow" can spit the underlying iterator into chunks

That's a very significant "somehow", because the contents of `std::iter::Map` are private.

One loose idea I've been pondering is to introduce some kind of `std::iter::SplitIterator` trait, which types like `Map` could implement themselves.  We could use this to split and evaluate in parallel, like you say.  However, I'm not sure if such a trait would have much use outside of this.

**Comment by cuviper** [comment] 2017-10-17 01:19
Let's close this as a dupe of #46.  I still like the splitting idea, but it will require work in `std` before we can do anything about it in `rayon`.

**Closed by cuviper** 2017-10-17 01:19 UTC
