### ISSUE TITLE
Parallelizing arbitrary iterators

### ISSUE THREAD

**Issue by jrmuizel** [rayon-rs/rayon#395] opened 2017-07-07 23:10 UTC
It would be nice to be able to parallelize programs like this:
```rust
    let f = File::open("foo.txt").unwrap();
    let f = BufReader::new(f);

    for line in f.lines().map(|x| something_very_expensive(x)) {
            println!("{}", line.unwrap());
    }
```
The assumption here is that `something_very_expensive` is expensive enough that we don't need to split the data into chunks larger than size 1.

**Comment by jrmuizel** [comment] 2017-07-11 13:40
This would help provide functionality similar to perl6's hyper() function.

**Comment by jrmuizel** [comment] 2017-07-21 15:55
It looks like https://github.com/TeXitoi/par-map provides this functionality

**Comment by bluss** [comment] 2017-07-27 21:27
FYI this has been discussed in rayon before, for example in #297

**Comment by cuviper** [comment] 2017-10-17 01:15
Closing as a duplicate of #46.

**Closed by cuviper** 2017-10-17 01:15 UTC
