### ISSUE TITLE
unexpected speedup when used next to crossbeam

### ISSUE THREAD

**Issue by nivkner** [rayon-rs/rayon#626] opened 2019-01-18 09:32 UTC
the following code behaves differently when the crossbeam version is used:
```
use rayon::prelude::*;

const CORES: usize = 4;

static DATA: &[u8] = include_bytes!("../data");

fn main() {
    println!("the size of the data is {} bytes", DATA.len());
    let (s_count, s_time) = measure_time(serial_doubles);
    let (r_count, r_time) = measure_time(rayon_doubles);
    println!(
        "serial: {} seconds and {} microseconds",
        s_time.as_secs(),
        s_time.subsec_micros()
    );
    println!(
        "rayon: {} seconds and {} microseconds",
        r_time.as_secs(),
        r_time.subsec_micros()
    );
    if DATA[0] == 0 {
        let (cb_count, cb_time) = measure_time(crossbeam_doubles);
        println!(
            "crossbeam: {} seconds and {} microseconds",
            cb_time.as_secs(),
            cb_time.subsec_micros()
        );
        assert_eq!(s_count, cb_count);
    }
    assert_eq!(s_count, r_count);
}

fn measure_time<F: FnOnce(&[u8]) -> usize>(fun: F) -> (usize, std::time::Duration) {
    let instant = std::time::Instant::now();
    let count = fun(DATA);
    (count, instant.elapsed())
}

fn serial_doubles(slice: &[u8]) -> usize {
    slice
        .windows(2)
        .filter(|slice| slice[0] == slice[1])
        .count()
}

fn rayon_doubles(slice: &[u8]) -> usize {
    slice
        .par_windows(2)
        .filter(|slice| slice[0] == slice[1])
        .count()
}

fn crossbeam_doubles(slice: &[u8]) -> usize {
    let part = slice.len() / CORES;
    crossbeam::scope(|scope| {
        let handles: Vec<_> = slice
            .chunks(part)
            .map(|chunk| scope.spawn(move |_| serial_doubles(chunk)))
            .collect();
        handles
            .into_iter()
            .map(|handle| handle.join().unwrap_or(0))
            .sum()
    })
    .unwrap()
}
```
as is the output is:
```
the size of the data is 22352731 bytes
serial: 0 seconds and 10752 microseconds
rayon: 0 seconds and 4703 microseconds
```
note that the crossbeam version isn't actually used at runtime.
when you replace the condition with `false` (thus that branch isn't compiled), the output is:
```
the size of the data is 22352731 bytes
serial: 0 seconds and 10713 microseconds
rayon: 0 seconds and 11821 microseconds
```
i checked if rayon is using a higher version of `crossbeam-deque` by replacing rayon with the version in #595  which uses version `0.6` but the same behavior occurred.

```
rustc 1.31.1 (b6c32da9b 2018-12-18)
binary: rustc
commit-hash: b6c32da9b0481e3e9d737153286b3ff8aa39a22c
commit-date: 2018-12-18
host: x86_64-unknown-linux-gnu
release: 1.31.1
LLVM version: 8.0
```

**Comment by cuviper** [comment] 2019-01-18 23:16
> when you replace the condition with `false` (thus that branch isn't compiled), the output is:

You mean the `if DATA[0] == 0` condition? The data is static, so LLVM should prune it just as well either way, assuming the first byte of your data is indeed 0. At least, I can't reproduce the issue you're seeing.

One thing you might try is `RUSTFLAGS=-Ccodegen-units=1`, which you can also set in Cargo.toml profiles. Sometimes the codegen splits can lead do different inlining decisions that impact performance. It didn't make any difference when I tried it though.

BTW, your crossbeam count is missing the case where the last item of one chunk equals the first item of the next. I caught this by first testing your code with data full of zeros.

**Comment by nivkner** [comment] 2019-01-19 07:16
i minimized the case:
```
use rayon::prelude::*;

static DATA: &[u8] = include_bytes!("../data");

fn main() {
    println!("the size of the data is {} bytes", DATA.len());
    let (s_count, s_time) = measure_time(serial_doubles);
    let (r_count, r_time) = measure_time(rayon_doubles);
    println!(
        "serial: {} seconds and {} microseconds",
        s_time.as_secs(),
        s_time.subsec_micros()
    );
    println!(
        "rayon: {} seconds and {} microseconds",
        r_time.as_secs(),
        r_time.subsec_micros()
    );
    crossbeam::scope(|scope| {
        let _ = scope.spawn(|_| 1);
    })
    .unwrap();
    assert_eq!(s_count, r_count);
}

fn measure_time<F: FnOnce(&[u8]) -> usize>(fun: F) -> (usize, std::time::Duration) {
    let instant = std::time::Instant::now();
    let count = fun(DATA);
    (count, instant.elapsed())
}

fn serial_doubles(slice: &[u8]) -> usize {
    slice
        .windows(2)
        .filter(|slice| slice[0] == slice[1])
        .count()
}

fn rayon_doubles(slice: &[u8]) -> usize {
    slice
        .par_windows(2)
        .filter(|slice| slice[0] == slice[1])
        .count()
}
```
this behavior happens only with `cargo run --release` (on debug build they look the same) and when `spawn` is used within the crossbeam scope.
try commenting out `let _ = scope.spawn(|_| 1);`

**Comment by cuviper** [comment] 2019-01-23 19:41
OK, I did some profiling.

With the `spawn` commented out, the rayon part ran in 46.2ms with this hotspot:

```text
rayon::iter::plumbing::Folder::consume_iter
Percent│
  0.78 │20:   test   %r9,%r9
       │    ↓ je     6b
       │      add    $0xffffffffffffffff,%r9
 51.46 │      mov    (%rsi),%rcx
  1.12 │      movzbl (%rdx),%eax
  0.99 │      cmp    0x1(%rdx),%al
       │    ↓ jne    38
  0.06 │      add    $0x1,%rcx
       │38:   add    $0x1,%rdx
 43.69 │      mov    %rcx,(%rsi)
  1.89 │      cmp    %r9,%r8
       │    ↑ jbe    20
```

With the spawn in place, the rayon part ran in 42.8ms with this hotspot:

```text
rayon::iter::plumbing::bridge_producer_consumer::helper
Percent│
  0.42 │160:   test   %rcx,%rcx
       │     ↓ je     18c
  4.91 │       add    $0xffffffffffffffff,%rcx
 50.72 │       movzbl (%rsi),%ebx
  0.20 │       xor    %edi,%edi
 17.80 │       cmp    0x1(%rsi),%bl
  0.15 │       lea    0x1(%rsi),%rsi
  2.20 │       sete   %dil
 23.61 │       add    %rdi,%rax
       │       cmp    %rcx,%rdx
       │     ↑ jbe    160
```

In the first case, `helper` calls `consumer_iter` separately, so the second case is more inlined. The loop was better optimized as a result, with fewer jumps and memory accesses.

With the following in `Cargo.toml` to restrict codegen units, I get consistent results with or without the `spawn`. So I think otherwise that added call just happens to perturb the division of units in a way that's detrimental to inlining.

```toml
[profile.release]
codegen-units = 1
```

**Comment by stjepang** [comment] 2019-01-23 19:47
@cuviper Can we fix the problem by sticking an `#[inline]` somewhere?

**Comment by cuviper** [comment] 2019-01-23 19:52
Maybe... but it's hard to say whether inlining `consume_iter` (for example) will be beneficial to everyone. This code happens to be a case where there's very little work for each item.

**Comment by nikomatsakis** [comment] 2019-04-17 17:37
As @cuviper's investigation seems to have resolved the mystery for now, we decided to close this issue -- it doesn't quite seem worth adding a `#[inline]` annotation.

**Closed by nikomatsakis** 2019-04-17 17:37 UTC
