### ISSUE TITLE
Parallelize work on buffered lines from a file

### ISSUE THREAD

**Issue by alubbe** [rayon-rs/rayon#297] opened 2017-04-07 15:54 UTC
Is it possible to use rayon to achieve something like this?
```rust
let input_file = File::open(&input_path).unwrap();
let mut reader = io::BufReader::new(input_file);
let result = reader.lines().par_iter().map(something_really_slow).reduce(...);
```
Essentially, can rayon 'poll' the iterator to grab new items and push them onto the work queue, and then run reduce? Or does rayon need full visibility on all work items and the total number of items to get started?

**Comment by cuviper** [comment] 2017-04-07 16:31
This is sort of the same question as #46.

Generally speaking, you don't want the rayon threads to do IO, because any blocking means it's not helping with the rest of the pool's jobs.

You might be able to do something with `spawn_async()` or `spawn_future_async()`, both currently hidden under `--features unstable`, but I don't have a ready example for you.

**Comment by bluss** [comment] 2017-04-08 23:15
I think it makes sense to use features for a general iterator → jobs feeder since they already solve the issue where it needs to stall the issuing of new jobs (reading lines) when many are still waiting.

**Comment by alubbe** [comment] 2017-04-09 04:04
@cuviper Thanks, I was not aware of spawn (https://docs.rs/rayon/0.7.0/rayon/struct.Scope.html#method.spawn). Are there by any chance any examples using it?
I'd very much like to run something similiar to fold&reduce. Since the tasks run sequentially once assigned to the thread pools, is it possible to define 'thread-globals' such as counters or hashmaps, and to receive a vector of these (one per pool) at the end, so that they may be combined/reduced into a final output?

@bluss I'm sorry, I don't quite follow - what features do you mean?

**Comment by alubbe** [comment] 2017-04-09 04:09
I also found an example of someone trying to use futures directly - how does this compare to rayon's spawn?
https://github.com/cetra3/apache_log/blob/master/src/main.rs#L148-L202

**Comment by cuviper** [comment] 2017-04-09 13:38
@alubbe You won't find online docs for the functions I mentioned, since they're behind a feature flag, but you can read their docs in the source: [`spawn_async`](https://github.com/nikomatsakis/rayon/blob/d2334bbc54ff34ca1697834b8e81c96edfc3dc6e/rayon-core/src/spawn_async/mod.rs#L11-L46) and [`spawn_future_async`](https://github.com/nikomatsakis/rayon/blob/d2334bbc54ff34ca1697834b8e81c96edfc3dc6e/rayon-core/src/spawn_async/mod.rs#L89-L97), and also [`Scope::spawn_future`](https://github.com/nikomatsakis/rayon/blob/master/rayon-core/src/scope/mod.rs#L288-L289).  The [`future/README.md`](https://github.com/nikomatsakis/rayon/blob/d2334bbc54ff34ca1697834b8e81c96edfc3dc6e/rayon-core/src/future/README.md) might also be interesting, although that's heavy on implementation details.

I'm afraid I don't have any real examples, as this is unstable stuff, but you could at least look at the [`test.rs`](https://github.com/nikomatsakis/rayon/blob/d2334bbc54ff34ca1697834b8e81c96edfc3dc6e/rayon-core/src/spawn_async/test.rs) for a basic idea.

**Comment by cuviper** [comment] 2017-04-09 13:41
> I think it makes sense to use features for a general iterator → jobs feeder since they already solve the issue where it needs to stall the issuing of new jobs (reading lines) when many are still waiting.

Yeah, I think we still do want something along these lines, but I'm not sure what it will look like.

**Comment by leshow** [comment] 2017-04-10 03:52
I was following along this issue and tried out `spawn_async` as it was done in the test file. I was able to get some code that compiled/ran fine with `std::thread::spawn`. And panicked, but compiled when run with `spawn_async`.

The code I wrote was silly, it executes synchronous requests inside of `spawn_async`, so it's not a great use of it. Should I collect more data and submit a bug report or is it still too unfinished?

**Comment by cuviper** [comment] 2017-04-10 04:32
Assuming it's not your own code that panicked, then yes, please file a bug with details!  It's definitely good to get reports even on these unstable features, so we can fix those issues before we stabilize it. :)

**Comment by nikomatsakis** [comment] 2017-04-11 09:14
@leshow I'm not aware of any bugs in `spawn_async`, so I'd like to know if you found something. =)

**Comment by beamspease** [comment] 2017-04-14 09:53
I think I have a similar question - I'm parsing protocol buffers from a stream. I parse the length and other header information. I then read the real data and can put it into a byte array, vector, etc. I'd then like the parsing of the bytes to the protocol buffer struct to happen in parallel. The interface I'd like to expose is an iterator (could be ParallelIterator) which provides the post-parsing items.

Alternatively, the iterator could provide a future that yields the post-parsed item.

**Comment by nikomatsakis** [comment] 2017-04-14 19:49
@beamspease the unstable `spawn_future_async` stuff is probably what you want. I do expect various changes there (i.e., it really is unstable), but mostly minor -- i.e., functions changing name and so forth.

**Comment by beamspease** [comment] 2017-04-19 00:20
I noticed while reading the tokio documenation that futures_cpupool has a spawn_fn (https://github.com/alexcrichton/futures-rs/blob/master/futures-cpupool/src/lib.rs#L212) that looks similar to spawn_future_async. Rayon looks like it has more sophisticated features eg par_iter. What's the difference between the two? Is the compatibility with tokio equivalent?

Sorry if this is derailing this ticket. >_>

**Comment by cuviper** [comment] 2017-10-17 01:14
Let's close the original request here as a dupe of #46.  If people still have other issues from the comment thread here, please open those separately!

**Closed by cuviper** 2017-10-17 01:14 UTC
