### ISSUE TITLE
Updating rayon-core to 1.4.0 broke a build

### ISSUE THREAD

**Issue by mathstuf** [rayon-rs/rayon#542] opened 2018-02-21 19:21 UTC
I work on the `git-checks` crate and an update to `rayon-core:1.4.0` broke the build somehow with this build error:

```
error[E0277]: the trait bound `str: std::cmp::PartialOrd<std::string::String>` is not satisfied
  --> src/checks/lfs_pointer.rs:32:27
   |
32 |             } else if key < &old_key {
   |                           ^ can't compare `str` with `std::string::String`
   |
   = help: the trait `std::cmp::PartialOrd<std::string::String>` is not implemented for `str`
   = note: required because of the requirements on the impl of `std::cmp::PartialOrd<&std::string::String>` for `&str`
```

I've set up commits which show the error with just a change in `Cargo.lock`: [working build](https://gitlab.kitware.com/ben.boeckel/rust-git-checks/commit/5d2c1291388cc4c1f7a6358a8635b644644fbe3b) [broken build](https://gitlab.kitware.com/ben.boeckel/rust-git-checks/commit/57d5b98401804684c422a5a010ddfc7e29949416). Why would updating `rayon-core`, a dependency only by transitivity, break the build of the `git-checks` crate?

Cc: @bradking

**Comment by cuviper** [comment] 2018-02-21 19:42
Very strange!  It doesn't look like rayon is involved in that part of the code at all.  I can reproduce this from rustc 1.17.0 through nightly-2018-02-18, so if this is a compiler bug, it's not a recent regression.  (Rust 1.16 and earlier fail to compile git-checks due to `static_in_const` feature.)

It works if you explicitly dereference that `String`, like `key < &*old_key`.  Auto-deref should normally figure this out, and again I have no idea why rayon-core would affect this.  I suggest filing an issue on [rust-lang/rust](https://github.com/rust-lang/rust)!

**Comment by mathstuf** [comment] 2018-02-21 19:46
Filed as rust-lang/rust#48406.

**Comment by cuviper** [comment] 2018-02-21 20:09
Thanks!  I'm going to close this, since you've now reproduced the problem without rayon at all.

**Closed by cuviper** 2018-02-21 20:09 UTC
